# Generated by Django 3.1 on 2020-08-25 00:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('math', 'math'), ('science', 'science'), ('english', 'english')], max_length=50)),
                ('course_number', models.IntegerField(null=True)),
                ('instructor_name', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.FloatField()),
            ],
            managers=[
                ('student', django.db.models.manager.Manager()),
            ],
        ),
    ]
